services:
  backend:
    build:
      context: ./backend
      target: production
    image: myapp/backend:latest
    container_name: myapp_backend
    environment:
      NODE_ENV: "production"
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always

  frontend:
    build:
      context: ./frontend
      target: production
    image: myapp/frontend:latest
    container_name: myapp_frontend
    environment:
      NODE_ENV: "production"
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
